name: Ocean Super-Bloom Daily Forecast

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev libcurl4-openssl-dev libssl-dev

      - name: Install R Packages
        run: |
          install.packages(c("dplyr", "rerddap", "mgcv", "lubridate", "ggplot2", "viridis", "scales", "maps", "jsonlite"))
        shell: Rscript {0}

      - name: Run Forecast Script
        run: Rscript run_forecast.R

      - name: Commit and Push Output
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f output/latest_forecast.csv  # Added -f here
          git add -f output/latest_forecast_map.png # Added -f here
          git commit -m "Daily Bloom Forecast Update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push